name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.5.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: node-core-utils
